Update release.yml
Bitergia/release-tools pull request #24
Opened 2021-02-18 11:48 UTC by vchrombie

This commit adds the support for automating the whole release process to the release github action.

Whenever there is a new release, the github actions builds the package, tests it with different python versions and uploads the package to pypi once the release is made public on GitHub.

demo: https://github.com/vchrombie/testing-release-tools/actions/runs/574315231

2021-02-18 12:24 UTC, vchrombie commented
There are 4 steps in the workflow and are inter-dependent on each other.

build -> test -> release (on github) -> publish

2021-02-18 16:05 UTC, sduenas requested changes
Check my minor comment. The PR looks good.

2021-02-18 16:26 UTC, vchrombie commented on .github/workflows/release.yml
> +          name: toolkit-dist
Yes, makes sense. I took the action from the toolkit experimentation and missed this. :smile:

2021-02-19 09:48 UTC, sduenas approved these changes
LGTM

2021-02-19 09:50 UTC, closed without merging