[WIP][tests] Update tests to increase coverage
Bitergia/release-tools pull request #29
Opened 2021-03-01 06:45 UTC by vchrombie

Add some more tests to increase coverage.

2021-03-10 10:13 UTC, sduenas requested changes
In general it looks good. Check my comments, though.

2021-03-10 10:13 UTC, sduenas commented on tests/test_publish.py
> +    def test_publish_repository_error_2(self, mock_project, mock_remove_unreleased_changelog):
The title of this test should explain better where the problem and what it's really testing.

2021-03-10 10:13 UTC, sduenas commented on tests/test_version.py
> +#!/usr/bin/env python3
This shouldn't be tested.

2021-03-10 10:25 UTC, vchrombie commented on tests/test_version.py
> +#!/usr/bin/env python3
Okay :+1:

2021-03-10 11:32 UTC, sduenas commented on tests/test_publish.py
> +    def test_remove_unreleased_changelog_entries_repository_error(self, mock_project, mock_remove_unreleased_changelog):
Would you mind to split this line? I think it's very long.

2021-03-11 09:02 UTC, sduenas approved these changes
LGTM

2021-03-11 09:06 UTC, merged