[repo] Fix root_path when a repo is a submodule
Bitergia/release-tools pull request #40
Opened 2022-01-20 08:55 UTC by jjmerchante

Basepath variable was referenced before assignment when the repository is a submodule.

2022-04-05 14:57 UTC, sduenas requested changes
The change looks ok but the PR needs two changes:

 - First, a changelog entry explaining the fix
 - Second, codecov action fails, apparently we need to upgrade it to v2 (I'm going to do this)

2022-04-06 11:43 UTC, sduenas requested changes
I think the changelog should contain a different message. Please check it:

2022-04-06 11:43 UTC, sduenas commented on releases/unreleased/fix-repo-when-is-a-submodule.yml
> +title: Fix repo when is a submodule
```suggestion
title: "Fix crash running the tools with on git submodules"
```

2022-04-06 11:43 UTC, sduenas commented on releases/unreleased/fix-repo-when-is-a-submodule.yml
> +  when the repository was a submodule.
The explanation should be other. What type of error we fix not what caused it. Remember that this is for users of the tools, not developers. What do you think?

```suggestion
notes: >
  Release tools didn't work when the project is under a git submodule.
```

2022-04-08 07:04 UTC, jjmerchante commented
Closing this issue. New proposal https://github.com/Bitergia/release-tools/pull/45

2022-04-08 07:04 UTC, closed without merging