Fix adding authors with the notes command
Bitergia/release-tools pull request #47
Opened 2022-06-01 10:50 UTC by jjmerchante

This commit fixes the issue that removes the last author
when the file AUTHORS doesn't end with and new line.

Fixes #46

2022-06-01 11:51 UTC, jjmerchante commented
That test is failing because it is not idempotent. Entries are sorted by issue ID but not by category. I will sort them also by category so the test will be idempotent.

2022-06-01 15:38 UTC, sduenas requested changes
I've tested it and it fixes the error. However, can you change the changelog description?

2022-06-01 15:38 UTC, sduenas commented on releases/unreleased/fix-notes-command-when-adding-authors.yml
> +title: Fix `notes` command when adding authors
```suggestion
title: Notes command removes last author
```

2022-06-02 09:43 UTC, sduenas approved these changes
LGTM

2022-06-02 09:44 UTC, closed without merging